#!/bin/bash

#SBATCH -J test_experiment
#SBATCH -p general
#SBATCH -o output.txt
#SBATCH -e log.err
#SBATCH --mail-type=ALL
#SBATCH --mail-user=sj110@iu.edu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --time=02:00:00
#SBATCH --mem=8G
#SBATCH -A general

srun gcc benchmark.c -o benchmark.out
srun ./benchmark.out

echo "\n\nLINPACK COMPLETE - RUNNING COMPLEXITY ANALYSIS...\n\n"

source activate crucible
srun python test.py
